# Generated by Django 3.2 on 2021-04-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bracelets', 'Bracelets'), ('Ensembles', 'Ensembles'), ('Bagues', 'Bagues'), ('Sollitaire', 'Sollitaire'), ('Serie', 'Serie'), ('Chichkhane', 'Chichkhane')], default='', max_length=50)),
                ('carats', models.PositiveIntegerField()),
                ('poids', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%y/%m/%d/')),
                ('imagebig', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%y/%m/%d/')),
                ('imageside', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%y/%m/%d/')),
                ('name', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
