# Generated by Django 3.2 on 2021-04-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210425_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bracelets', 'Bracelets'), ('Ensembles', 'Ensembles'), ('Bagues', 'Bagues'), ('Sollitaire', 'Sollitaire'), ('Serie 3P', 'Serie 3P'), ('Chichkhane', 'Chichkhane')], default='', max_length=50),
        ),
    ]
