# Generated by Django 3.2 on 2021-04-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bracelets', 'Bracelets'), ('Ensembles', 'Ensembles'), ('Bagues', 'Bagues'), ('Sollitaire', 'Sollitaire'), ('Serie', 'Serie'), ('Chichkhane', 'Chichkhane')], default='', max_length=50),
        ),
    ]
