# Generated by Django 3.2 on 2021-04-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imageslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagehome', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%y/%m/%d/')),
                ('name', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
